Update cmd.js
fastify/create-fastify pull request #58
Opened 2024-09-27 01:03 UTC by qbytx

### PR Description:

- **Directory Handling**: Uses `path.resolve()` for consistent paths; defaults to the current directory (`.`) when no valid argument is provided.
- **Code Cleanup**:
  - Added semicolons to follow [ECMAScript guidelines](https://tc39.es/ecma262/multipage/ecmascript-language-lexical-grammar.html#sec-automatic-semicolon-insertion), preventing ASI issues.
  - Removed redundant spread operator from `args` initialization.

These changes improve script reliability and readability. Let me know if you need any adjustments.

#### Checklist

- [ x ] run `npm run test` and `npm run benchmark`
// tests passed for cmd.js

- [ ] tests and/or benchmarks are included
// no features added

- [ ] documentation is changed or added
// documentation is unchanged

- [ x ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-09-27 07:53 UTC, Fdawgs requested changes

2024-09-27 07:53 UTC, Fdawgs commented on cmd.js
> +'use strict';
```suggestion

'use strict';
```

2024-09-27 07:53 UTC, Fdawgs commented on cmd.js
> +const path = require('path');
```suggestion
const { resolve } = require('node:path');
```

2024-09-27 07:53 UTC, Fdawgs commented on cmd.js
> +const directory = (!args[0] || args[0] === "" || args[0].startsWith('-')) ? '.' : path.resolve(args[0]);
```suggestion
const directory = (!args[0] || args[0] === "" || args[0].startsWith('-')) ? '.' : resolve(args[0]);
```

2024-09-28 06:56 UTC, mcollina commented
Can you avoid any formatting changes? We don't use semicolons in this org. Please restore all the spread operators too.

2024-09-28 06:57 UTC, mcollina commented
CI is failing.

2024-09-28 14:55 UTC, qbytx commented
> Can you avoid any formatting changes? We don't use semicolons in this org. Please restore all the spread operators too.

Certainly; just pushed a commit. 👍 and I will address any continuing CI failures soon

2024-10-01 17:05 UTC, qbytx commented
Will address these last CI issues this week

2025-01-12 10:55 UTC, Fdawgs commented
@qbytx are you still wanting to change this or can this be closed? We plan on archiving this repo.

2025-01-15 14:10 UTC, Fdawgs commented
Closing due to inactivity.

2025-01-15 14:10 UTC, closed without merging